### ISSUE TITLE
add a sound  when button/buttons are clicked 

### ISSUE THREAD

**Issue by oshadavloger** [hirusha-adi/Downloader#1]
play a sound when a button is clicked (maybe ricks voice), since the downloader is in the Rick and Morty theme, it would be fine to add some sounds effects too,

**Comment by hirusha-adi** [comment]
ok. working on it!

**Comment by hirusha-adi** [comment]
Running the audio and the function on a single thread is not the best thing to do.. so the audio will be played on a new Thread while the download is going on

**Comment by hirusha-adi** [comment]
Done, check out version 0.4.1 - Its kind of resource heavy... so it wont be in next releases
